---
# tasks file for role_httpd

- package: 
    name: "{{ item }}"
  loop: "{{ x }}" 

- copy:
    src: "web.php" 
    dest: "/var/www/html"   

- service: 
    name: "httpd"
    state: started
      

